// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY02LsZ4CSt6ZY5qyjj_M-eQkKDYbEiPM',
    appId: '1:375512262678:web:46b3b71c3d54f2d8dead37',
    messagingSenderId: '375512262678',
    projectId: 'live-score-app-c5055',
    authDomain: 'live-score-app-c5055.firebaseapp.com',
    storageBucket: 'live-score-app-c5055.firebasestorage.app',
    measurementId: 'G-CX05W9S7CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKEpGQoeBHSOVJQC7l2-MKhM7s5CtaMqc',
    appId: '1:375512262678:android:e5c648f81a7d750bdead37',
    messagingSenderId: '375512262678',
    projectId: 'live-score-app-c5055',
    storageBucket: 'live-score-app-c5055.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP5gM8dJL4cLCrKP9faxEuQiicN3uq6Iw',
    appId: '1:375512262678:ios:6bab9825512c399bdead37',
    messagingSenderId: '375512262678',
    projectId: 'live-score-app-c5055',
    storageBucket: 'live-score-app-c5055.firebasestorage.app',
    iosBundleId: 'com.example.craftyBay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCP5gM8dJL4cLCrKP9faxEuQiicN3uq6Iw',
    appId: '1:375512262678:ios:6bab9825512c399bdead37',
    messagingSenderId: '375512262678',
    projectId: 'live-score-app-c5055',
    storageBucket: 'live-score-app-c5055.firebasestorage.app',
    iosBundleId: 'com.example.craftyBay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY02LsZ4CSt6ZY5qyjj_M-eQkKDYbEiPM',
    appId: '1:375512262678:web:50630d87670ee163dead37',
    messagingSenderId: '375512262678',
    projectId: 'live-score-app-c5055',
    authDomain: 'live-score-app-c5055.firebaseapp.com',
    storageBucket: 'live-score-app-c5055.firebasestorage.app',
    measurementId: 'G-SVZ6CS1V8J',
  );
}
